<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_JOG</name>
   <tag></tag>
   <elementGuidId>b1b8ac0d-1fe0-4687-8ce2-fe43cc7e075e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/div[@class=&quot;autocomplete-result&quot;]/div[1]/b[1][count(. | //*[(text() = 'JOG' or . = 'JOG')]) = count(//*[(text() = 'JOG' or . = 'JOG')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//b[(text() = 'JOG' or . = 'JOG')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JOG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;autocomplete-result&quot;]/div[1]/b[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'JOG' or . = 'JOG')]</value>
   </webElementXpaths>
</WebElementEntity>
