<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CGK</name>
   <tag></tag>
   <elementGuidId>325d5b69-6a29-4ffd-8b0b-2a664cbd0791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/div[@class=&quot;autocomplete-result&quot;]/div[1]/b[1][count(. | //*[(text() = 'CGK' or . = 'CGK')]) = count(//*[(text() = 'CGK' or . = 'CGK')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//b[(text() = 'CGK' or . = 'CGK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CGK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;autocomplete-result&quot;]/div[1]/b[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'CGK' or . = 'CGK')]</value>
   </webElementXpaths>
</WebElementEntity>
